baseURL: "https://unrivaled-chimera-daa522.netlify.app"
languageCode: en-en
title: Repatriation Site
theme: PaperModX
output:
  blogdown::html_page:
    toc:true
params:
  TocSide: 'left'
  defaultTheme: auto  
      
  
